char *INDEX_HTML[] = {
    "<!DOCTYPE html>",
    "<html>",
    "<head>",
    "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=9\"/>",
    "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
    "    <title>HexaMods Loader</title>",
    "    <style>",
    "        body {",
    "            background-color: #020014;",
    "            color: #e0e0e0;",
    "            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
    "            margin: 0;",
    "            padding: 20px;",
    "            background-image: linear-gradient(135deg, #020014 0%, #0a0a2a 100%);",
    "            min-height: 100vh;",
    "        }",
    "        .container {",
    "            max-width: 800px;",
    "            margin: 0 auto;",
    "        }",
    "        h1 {",
    "            color: #FF4500;",
    "            text-align: center;",
    "            font-family: 'Courier New', monospace;",
    "            text-transform: uppercase;",
    "            letter-spacing: 4px;",
    "            text-shadow: 0 0 10px rgba(255, 69, 0, 0.5);",
    "            margin-bottom: 5px;",
    "        }",
    "        .subtitle {",
    "            text-align: center;",
    "            color: #888;",
    "            font-size: 0.9em;",
    "            margin-bottom: 30px;",
    "            font-family: monospace;",
    "        }",
    "        .card {",
    "            background: rgba(20, 20, 40, 0.8);",
    "            border: 1px solid #333;",
    "            border-left: 4px solid #FF4500;",
    "            border-radius: 8px;",
    "            padding: 20px;",
    "            margin-bottom: 20px;",
    "            box-shadow: 0 4px 15px rgba(0,0,0,0.5);",
    "        }",
    "        h2 {",
    "            color: #fff;",
    "            margin-top: 0;",
    "            border-bottom: 1px solid #333;",
    "            padding-bottom: 10px;",
    "            font-size: 1.2em;",
    "        }",
    "        .key-label {",
    "            color: #FF4500;",
    "            font-weight: bold;",
    "            font-size: 0.8em;",
    "            text-transform: uppercase;",
    "            margin-bottom: 5px;",
    "        }",
    "        .key-value {",
    "            background: #000;",
    "            color: #00ff41;",
    "            padding: 10px;",
    "            border-radius: 4px;",
    "            font-family: 'Consolas', 'Courier New', monospace;",
    "            word-break: break-all;",
    "            border: 1px solid #333;",
    "            margin-bottom: 15px;",
    "        }",
    "        .btn-grid {",
    "            display: grid;",
    "            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));",
    "            gap: 10px;",
    "        }",
    "        button {",
    "            background: transparent;",
    "            border: 1px solid #FF4500;",
    "            color: #FF4500;",
    "            padding: 12px;",
    "            border-radius: 4px;",
    "            cursor: pointer;",
    "            font-weight: bold;",
    "            text-transform: uppercase;",
    "            transition: all 0.3s ease;",
    "            width: 100%;",
    "        }",
    "        button:hover {",
    "            background: #FF4500;",
    "            color: #fff;",
    "            box-shadow: 0 0 15px #FF4500;",
    "        }",
    "        .footer {",
    "            text-align: center;",
    "            margin-top: 40px;",
    "            font-size: 0.8em;",
    "            color: #555;",
    "        }",
    "        a { color: #FF4500; text-decoration: none; }",
    "        a:hover { text-decoration: underline; }",
    "    </style>",
    "</head>",
    "<body>",
    "    <div class=\"container\">",
    "        <h1>HexaMods Loader</h1>",
    "        <div class=\"subtitle\">v1.0 // Coded by DAYBR3AK // RGH 4 Ever</div>",

    "        <div class=\"card\">",
    "            <h2>System Identity</h2>",
    "            <div class=\"key-label\">CPU Key</div>",
    "            <div class=\"key-value\">",
    "CPU_KEY",
    "            </div>",
    "            <div class=\"key-label\">DVD Key</div>",
    "            <div class=\"key-value\">",
    "DVD_KEY",
    "            </div>",
    "        </div>",

    "        <div class=\"card\">",
    "            <h2>NAND &amp; Tools</h2>",
    "            <p style=\"color:#aaa; font-size:0.9em;\">Backup your system files securely.</p>",
    "            <div class=\"btn-grid\">",
    "                <button onclick=\"window.location.href='/FLASH'\">Download Flash</button>",
    "                <button onclick=\"window.location.href='/KV'\">Key Vault</button>",
    "                <button onclick=\"window.location.href='/FUSE'\">Fuses</button>",
    "                <button onclick=\"window.location.href='/LOG'\">Startup Log</button>",
    "            </div>",
    "        </div>",

    "        <div class=\"card\" style=\"border-left-color: #ff0000;\">",
    "            <h2 style=\"color: #ffaaaa;\">Power Controls</h2>",
    "            <div class=\"btn-grid\">",
    "                <button onclick=\"window.location.href='/REBOOT'\" style=\"border-color: #fff; color: #fff;\">Reboot</button>",
    "                <button onclick=\"window.location.href='/SHUTDOWN'\" style=\"border-color: #ff0000; color: #ff0000;\">Shutdown</button>",
    "            </div>",
    "        </div>",

    "        <div class=\"footer\">",
    "            HexaMods Loader &copy; 2025 DAYBR3AK<br>",
    "            <a href=\"http://www.free60.org/\" target=\"_blank\">Free60</a> |",
    "            <a href=\"http://www.libxenon.org/\" target=\"_blank\">LibXenon</a>",
    "        </div>",
    "    </div>",
    "</body>",
    "</html>",
};
